import Foundation

/// Imported connection-link payload. Field names/casing match the iOS
/// ConnectionSettings (AppConfig.swift) and quick_link.py output, so links
/// generated by the iOS app or quick_link.py import here unchanged.
/// iOS/quick_link.py wrap the settings as {"settings":{…},"type":…,"version":…}.
/// Some older links are flat. We handle both.
struct LinkEnvelope: Codable {
    var settings: ImportedSettings?
    var type: String?
    var version: Int?
}

struct ImportedSettings: Codable {
    var serverName: String?
    var privateKey: String?
    var peerPublicKey: String?
    var presharedKey: String?
    var tunnelAddress: String?
    var allowedIPs: String?
    var vkLink: String?
    var peerAddress: String?
    var useDTLS: Bool?
    var useWrap: Bool?
    var wrapKeyHex: String?
    var useSrtp: Bool?
    var useUDP: Bool?
    var useWrapA: Bool?
    var wrapAPassword: String?
    var turnServerOverride: String?
    var dnsServers: String?
    var numConnections: Int?
    var vkAuth: Bool?
    var useWrapS: Bool?
}

enum ConnectionLink {
    static let schemes: Set<String> = ["vkturnproxy", "wdtt", "freeturn"]

    /// Parse a `vkturnproxy://import?data=<base64>` link OR a bare base64 blob.
    static func parse(_ raw: String) -> ImportedSettings? {
        let s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        var b64: String? = nil

        if let url = URLComponents(string: s), let scheme = url.scheme?.lowercased(),
           schemes.contains(scheme) {
            b64 = url.queryItems?.first(where: { $0.name == "data" })?.value
            // some generators put the payload in the path/host
            if b64 == nil { b64 = s.components(separatedBy: "data=").last }
        } else {
            b64 = s   // bare base64 pasted
        }
        guard let payload = b64, let data = decodeBase64(payload) else { return nil }
        let dec = JSONDecoder()
        // Preferred shape: {"settings":{…},"type":"connection","version":1}
        if let env = try? dec.decode(LinkEnvelope.self, from: data), let s = env.settings {
            return s
        }
        // Fallback: a flat settings object.
        return try? dec.decode(ImportedSettings.self, from: data)
    }

    private static func decodeBase64(_ in0: String) -> Data? {
        var c = in0.trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        // pad to a multiple of 4
        let rem = c.count % 4
        if rem > 0 { c += String(repeating: "=", count: 4 - rem) }
        return Data(base64Encoded: c, options: [.ignoreUnknownCharacters])
    }

    /// Apply an imported payload onto the model (nil = keep current value,
    /// matching iOS nil-preserve semantics).
    @MainActor
    static func apply(_ s: ImportedSettings, to model: AppModel) {
        var p = model.profile
        if let v = s.serverName, !v.isEmpty { p.serverName = v }
        if let v = s.privateKey { p.privateKey = v }
        if let v = s.peerPublicKey { p.peerPublicKey = v }
        if let v = s.presharedKey { p.presharedKey = v }
        if let v = s.tunnelAddress { p.tunnelAddress = v }
        if let v = s.peerAddress { p.peerAddress = v }
        if let v = s.dnsServers { p.dnsServers = v }
        if let v = s.numConnections { p.numConnections = v }
        if let v = s.turnServerOverride { p.turnServerOverride = v }
        // mode: SRTP wins, then UDP, else legacy DTLS/TCP
        if s.useSrtp == true { p.mode = .srtp }
        else if s.useUDP == true { p.mode = .udp }
        else if s.useDTLS == true { p.mode = .dtls }
        model.profile = p
        if let v = s.vkLink, !v.isEmpty { model.vkLink = v }
        model.save()
        model.log("[import] профиль применён: \(p.serverName) \(p.peerAddress) [\(p.mode.label)]")
    }
}
